### ISSUE TITLE
0.12 compatibility

### ISSUE THREAD

**Issue by janegilring** [GSLabDev/terraform-provider-scvmm#2]
Hi,

I am trying to use the provider with Terraform 0.12 beta 2, and get this error:
terraform init

Initializing the backend...

Initializing provider plugins...
- Checking for available provider plugins...

Provider "scvmm" not available for installation.

A provider named "scvmm" could not be found in the Terraform Registry.

This may result from mistyping the provider name, or the given provider may
be a third-party provider that cannot be installed automatically.

In the latter case, the plugin must be installed manually by locating and
downloading a suitable distribution package and placing the plugin's executable
file in the following directory:
    terraform.d/plugins/windows_amd64

Terraform detects necessary plugins by inspecting the configuration and state.
To view the provider versions requested by each module, run
"terraform providers".

Error: no provider exists with the given name

I tried to copy the contents of the scvmm-folder in the repo to the following location:
C:\Users\%username%AppData\Roaming\terraform.d\plugins\windows_amd64\scvmm

However, that did not make any difference.

**Comment by adrianleh** [comment]
Hi @janegilring,

the way I got this to work is to manually install the plugin (as, now correctly, described in https://github.com/adrianleh/terraform-provider-scvmm/tree/fix-build-instructions).

This is *NOT* an issue to do with terraform 0.12, as the plugin is simply not available for any terraform version at the moment; but this is something the maintainers must fix

Cheers!

**Comment by janegilring** [comment]
Excellent, thanks!
